### ISSUE TITLE
[Jenkins Artifactory Plug-in] : not support hyphen (-) in noProxyHostPatterns

### ISSUE THREAD

**Issue by edahenit** [jenkinsci/jfrog-plugin#34]
### Describe the bug

Hello,

We are using the latest version of the Jenkins JFrog plugin, and our Artifactory DNS contains a hyphen (https://bar-artifactory.mycompany.com/).
We have added this DNS to the list of "No Proxy Hosts" in Jenkins configuration to bypass the proxy, but it has not worked.

Upon investigation, we have discovered that the plugin does not support DNS containing hyphens (-) in the noProxyHostPatterns [jfrog-plugin/src/main/java/io/jenkins/plugins/jfrog/configuration/JenkinsProxyConfiguration.java at 5f26fa7dc608a1f588633a272bbb8a95868b8c0a · jenkinsci/jfrog-plugin (github.com)](https://github.com/jenkinsci/jfrog-plugin/blob/5f26fa7dc608a1f588633a272bbb8a95868b8c0a/src/main/java/io/jenkins/plugins/jfrog/configuration/JenkinsProxyConfiguration.java#L18C60-L18C93).

We kindly request that you urgently address this issue.

Best regards,

### Current behavior

Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to jfrog-test-34-mswgb-skkjf-00g4d
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1000)
		at hudson.FilePath.act(FilePath.java:1192)
		at hudson.FilePath.act(FilePath.java:1181)
		at io.jenkins.plugins.jfrog.BinaryInstaller.performJfrogCliInstallation(BinaryInstaller.java:53)
		at io.jenkins.plugins.jfrog.ArtifactoryInstaller.performInstallation(ArtifactoryInstaller.java:67)
		at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:70)
		at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:109)
		at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:221)
		at io.jenkins.plugins.jfrog.JfrogInstallation.forNode(JfrogInstallation.java:50)
		at io.jenkins.plugins.jfrog.JfrogInstallation.forNode(JfrogInstallation.java:32)
		at org.jenkinsci.plugins.workflow.steps.ToolStep$Execution.run(ToolStep.java:157)
		at org.jenkinsci.plugins.workflow.steps.ToolStep$Execution.run(ToolStep.java:138)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 8499e383-19d6-48fc-a924-b120415d9b6e
java.io.IOException: JFrog service failed. Received 407: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>

### Reproduction steps

We are using the latest version of the Jenkins JFrog plugin, and our Artifactory DNS contains a hyphen (https://bar-artifactory.mycompany.com/).

### Expected behavior

Upon investigation, we have discovered that the plugin does not support DNS containing hyphens (-) in the noProxyHostPatterns [jfrog-plugin/src/main/java/io/jenkins/plugins/jfrog/configuration/JenkinsProxyConfiguration.java at 5f26fa7dc608a1f588633a272bbb8a95868b8c0a · jenkinsci/jfrog-plugin (github.com)](https://github.com/jenkinsci/jfrog-plugin/blob/5f26fa7dc608a1f588633a272bbb8a95868b8c0a/src/main/java/io/jenkins/plugins/jfrog/configuration/JenkinsProxyConfiguration.java#L18C60-L18C93).

### JFrog plugin version

1.5.0

### JFrog CLI version

2.59.1

### Operating system type and version

Linux

### JFrog Artifactory version

7.77.11

### JFrog Xray version

3.94.5

**Comment by yahavi** [comment]
@edahenit 
Thank you for using the Jenkins JFrog plugin.
This issue has already been resolved in version [1.5.1](https://github.com/jfrog/jenkins-jfrog-plugin/releases/tag/jfrog-1.5.1) of the plugin.
Please upgrade and let us know your feedback.
