### ISSUE TITLE
Include JCasC Examples

### ISSUE THREAD

**Issue by adamerstelle** [jenkinsci/jfrog-plugin#7]
### Is your feature request related to a problem? Please describe.

I'm having trouble configuring this plugin when using Jenkins Configuration as Code. I've done my best looking at the plugin code to try to determine what my config should be, however when Jenkins starts up there is an issue.

Using the config below, Jenkins doesn't seem to pull in the install source and I always have to set it manually after a restart.

```
unclassified:
  jFrogPlatformBuilder:
    jfrogInstances:
      - serverId: "artifactory"
        platformUrl: https://mycompany.jfrog.io/
        credentialsConfig:
          credentialsId: "artifactory-account"
tool:
  jfrogInstallation:
    installations:
      - name: "jfrog-cli"
        home: ""
        properties:
          - installSource:
              installers:
                - releasesInstaller:
                    id: "latestJfrogInstaller"
```
(I'm aiming to have a very simple tool where it just grabs the latest from the releases site.)

I've also tried to use Jenkin's ability to show me the current JCasC after manually setting everything up, however I get a stack trace in the output instead of something helpful.

```
jFrogPlatformBuilder:
    jfrogInstances: |-
      FAILED TO EXPORT
      io.jenkins.plugins.jfrog.configuration.JFrogPlatformBuilder$DescriptorImpl#jfrogInstances: io.jenkins.plugins.casc.ConfiguratorException: Can't read attribute 'platformUrl' from io.jenkins.plugins.jfrog.configuration.JFrogPlatformInstance@1e23abad
        at io.jenkins.plugins.casc.Attribute._getValue(Attribute.java:461)
        at io.jenkins.plugins.casc.Attribute.getValue(Attribute.java:235)
        at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:289)
        at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:328)
        at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:257)
        at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:183)
        at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:114)
        at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.lambda$describe$3(GlobalConfigurationCategoryConfigurator.java:107)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:107)
        at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:33)
```

The tool itself gives me very little when looking at the same screen:
```
tool:
  jfrog:
    installations:
    - name: "jfrog-cli"
  sonarRunnerInstallation:
    installations:
    - name: "sonarScanner"
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "4.7.0.2747"
```
(I included the output from Sonar Qube's tool to show what I think I'm looking for.

### Describe the solution you'd like to see

It would be really nice to see an example of how to configure the "platform builder" and the "jFrog Installation" tool.

### Describe alternatives you've considered

I've come as close as I can with Config. Currently, when a Job fails (after a jenkins restart) I have to login to jenkins and add the missing config...restart my job.

**Comment by psimms-r7** [comment]
I agree we definitely need some proper documentation and also the FAILED TO EXPORT issue when looking at the config as code directly in the jenkins UI as stated above

I was playing around with the config and was able to get this to work, still with the failed to export error, however the configuration was setup as expected

```
unclassified:
  jFrogPlatformBuilder:
    jfrogInstances:
    - artifactoryUrl: "https://artifacts.example.com/artifactory"
      credentialsConfig:
        credentialsId: "artifactory-example-credentials"
      distributionUrl: "https://artifacts.example.com/distribution"
      id: "artifacts"
      platformUrl: "https://artifacts.example.com"

tool:
  jfrog:
    installations:
    - name: "jfrog-cli"
      properties:
      - installSource:
          installers:
          - "releasesInstaller"
```

**Comment by madelaney** [comment]
There is open PR (https://github.com/jfrog/jenkins-jfrog-plugin/issues/22), on the Jfrog fork to address this as well.

**Comment by yahavi** [comment]
Hi @madelaney & @adamerstelle,
Jenkins JFrog plugin 1.1.0 is released. This version includes support for JCasC.
Find the documentation in the README: https://github.com/jfrog/jenkins-jfrog-plugin#jenkins-configuration-as-code
We'd appreciate your feedback on that!
